# Run this Docker compose file using `docker-compose up -d --build`
# No need specify version 2 or 3 in latest Compose specification

services:
  # Backend service (FastAPI)
  backend:
    build: backend_fastAPI
    image: e2e-automl-backend:latest     
    ports:
      - "8000:8000"
      - "54321:54321"
    volumes:
      - ./backend:/app/backend_fastAPI
    networks:
      - project_network

  # Frontend service (Streamlit UI)
  frontend:
    build: frontend_Streamlit
    image: e2e-automl-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend_Streamlit
    depends_on: 
    - backend
    networks:
      - project_network

networks:
  project_network: